export const kanaChart = [
  {
    row: "vowels",
    characters: { あ: "a", い: "i", う: "u", え: "e", お: "o" },
  },
  {
    row: "kRow",
    characters: { か: "ka", き: "ki", く: "ku", け: "ke", こ: "ko" },
  },
  {
    row: "gRow",
    characters: { が: "ga", ぎ: "gi", ぐ: "gu", げ: "ge", ご: "go" },
  },
  {
    row: "sRow",
    characters: { さ: "sa", し: "shi", す: "su", せ: "se", そ: "so" },
  },
  {
    row: "zRow",
    characters: { ざ: "za", じ: "ji", ず: "zu", ぜ: "ze", ぞ: "zo" },
  },
  {
    row: "tRow",
    characters: { た: "ta", ち: "chi", つ: "tsu", て: "te", と: "to" },
  },
  {
    row: "dRow",
    characters: { だ: "da", ぢ: "ji", づ: "zu", で: "de", ど: "do" },
  },
  {
    row: "nRow",
    characters: { な: "na", に: "ni", ぬ: "nu", ね: "ne", の: "no" },
  },
  {
    row: "hRow",
    characters: { は: "ha", ひ: "hi", ふ: "fu", へ: "he", ほ: "ho" },
  },
  {
    row: "bRow",
    characters: { ば: "ba", び: "bi", ぶ: "bu", べ: "be", ぼ: "bo" },
  },
  {
    row: "pRow",
    characters: { ぱ: "pa", ぴ: "pi", ぷ: "pu", ぺ: "pe", ぽ: "po" },
  },
  {
    row: "mRow",
    characters: { ま: "ma", み: "mi", む: "mu", め: "me", も: "mo" },
  },
  { row: "yRow", characters: { や: "ya", ゆ: "yu", よ: "yo" } },
  {
    row: "rRow",
    characters: { ら: "ra", り: "ri", る: "ru", れ: "re", ろ: "ro" },
  },
  { row: "wRow", characters: { わ: "wa", を: "wo" } },
  { row: "specialN", characters: { ん: "n/m" } },
  {
    row: "combinations",
    characters: {
      きゃ: "kya",
      きゅ: "kyu",
      きょ: "kyo",
      ぎゃ: "gya",
      ぎゅ: "gyu",
      ぎょ: "gyo",
      しゃ: "sha",
      しゅ: "shu",
      しょ: "sho",
      じゃ: "ja",
      じゅ: "ju",
      じょ: "jo",
      ちゃ: "cha",
      ちゅ: "chu",
      ちょ: "cho",
      にゃ: "nya",
      にゅ: "nyu",
      にょ: "nyo",
      ひゃ: "hya",
      ひゅ: "hyu",
      ひょ: "hyo",
      びゃ: "bya",
      びゅ: "byu",
      びょ: "byo",
      ぴゃ: "pya",
      ぴゅ: "pyu",
      ぴょ: "pyo",
      みゃ: "mya",
      みゅ: "myu",
      みょ: "myo",
      りゃ: "rya",
      りゅ: "ryu",
      りょ: "ryo",
    },
  },
];
