export const kanaChart = [
  {
    row: "vowels",
    characters: { あ: "a", い: "i", う: "u", え: "e", お: "o" },
  },
  {
    row: "kRow",
    characters: { か: "ka", き: "ki", く: "ku", け: "ke", こ: "ko" },
  },
  {
    row: "gRow",
    characters: { が: "ga", ぎ: "gi", ぐ: "gu", げ: "ge", ご: "go" },
  },
  {
    row: "sRow",
    characters: { さ: "sa", し: "shi", す: "su", せ: "se", そ: "so" },
  },
  {
    row: "zRow",
    characters: { ざ: "za", じ: "ji", ず: "zu", ぜ: "ze", ぞ: "zo" },
  },
  {
    row: "tRow",
    characters: { た: "ta", ち: "chi", つ: "tsu", て: "te", と: "to" },
  },
  {
    row: "dRow",
    characters: { だ: "da", ぢ: "ji", づ: "zu", で: "de", ど: "do" },
  },
  {
    row: "nRow",
    characters: { な: "na", に: "ni", ぬ: "nu", ね: "ne", の: "no" },
  },
  {
    row: "hRow",
    characters: { は: "ha", ひ: "hi", ふ: "fu", へ: "he", ほ: "ho" },
  },
  {
    row: "bRow",
    characters: { ば: "ba", び: "bi", ぶ: "bu", べ: "be", ぼ: "bo" },
  },
  {
    row: "pRow",
    characters: { ぱ: "pa", ぴ: "pi", ぷ: "pu", ぺ: "pe", ぽ: "po" },
  },
  {
    row: "mRow",
    characters: { ま: "ma", み: "mi", む: "mu", め: "me", も: "mo" },
  },
  { row: "yRow", characters: { や: "ya", ゆ: "yu", よ: "yo" } },
  {
    row: "rRow",
    characters: { ら: "ra", り: "ri", る: "ru", れ: "re", ろ: "ro" },
  },
  { row: "wRow", characters: { わ: "wa", を: "wo" } },
  { row: "specialN", characters: { ん: "n/m" } },
  {
    row: "combinations",
    characters: {
      きゃ: "kya",
      きゅ: "kyu",
      きょ: "kyo",
      ぎゃ: "gya",
      ぎゅ: "gyu",
      ぎょ: "gyo",
      しゃ: "sha",
      しゅ: "shu",
      しょ: "sho",
      じゃ: "ja",
      じゅ: "ju",
      じょ: "jo",
      ちゃ: "cha",
      ちゅ: "chu",
      ちょ: "cho",
      にゃ: "nya",
      にゅ: "nyu",
      にょ: "nyo",
      ひゃ: "hya",
      ひゅ: "hyu",
      ひょ: "hyo",
      びゃ: "bya",
      びゅ: "byu",
      びょ: "byo",
      ぴゃ: "pya",
      ぴゅ: "pyu",
      ぴょ: "pyo",
      みゃ: "mya",
      みゅ: "myu",
      みょ: "myo",
      りゃ: "rya",
      りゅ: "ryu",
      りょ: "ryo",
    },
  },
];

export const katakanaChart = [
  {
    row: "vowels",
    characters: { ア: "a", イ: "i", ウ: "u", エ: "e", オ: "o" },
  },
  {
    row: "kRow",
    characters: { カ: "ka", キ: "ki", ク: "ku", ケ: "ke", コ: "ko" },
  },
  {
    row: "gRow",
    characters: { ガ: "ga", ギ: "gi", グ: "gu", ゲ: "ge", ゴ: "go" },
  },
  {
    row: "sRow",
    characters: { サ: "sa", シ: "shi", ス: "su", セ: "se", ソ: "so" },
  },
  {
    row: "zRow",
    characters: { ザ: "za", ジ: "ji", ズ: "zu", ゼ: "ze", ゾ: "zo" },
  },
  {
    row: "tRow",
    characters: { タ: "ta", チ: "chi", ツ: "tsu", テ: "te", ト: "to" },
  },
  {
    row: "dRow",
    characters: { ダ: "da", ヂ: "ji", ヅ: "zu", デ: "de", ド: "do" },
  },
  {
    row: "nRow",
    characters: { ナ: "na", ニ: "ni", ヌ: "nu", ネ: "ne", ノ: "no" },
  },
  {
    row: "hRow",
    characters: { ハ: "ha", ヒ: "hi", フ: "fu", ヘ: "he", ホ: "ho" },
  },
  {
    row: "bRow",
    characters: { バ: "ba", ビ: "bi", ブ: "bu", ベ: "be", ボ: "bo" },
  },
  {
    row: "pRow",
    characters: { パ: "pa", ピ: "pi", プ: "pu", ペ: "pe", ポ: "po" },
  },
  {
    row: "mRow",
    characters: { マ: "ma", ミ: "mi", ム: "mu", メ: "me", モ: "mo" },
  },
  { row: "yRow", characters: { ヤ: "ya", ユ: "yu", ヨ: "yo" } },
  {
    row: "rRow",
    characters: { ラ: "ra", リ: "ri", ル: "ru", レ: "re", ロ: "ro" },
  },
  { row: "wRow", characters: { ワ: "wa", ヲ: "wo" } },
  { row: "specialN", characters: { ン: "n/m" } },
  {
    row: "combinations",
    characters: {
      キャ: "kya",
      キュ: "kyu",
      キョ: "kyo",
      ギャ: "gya",
      ギュ: "gyu",
      ギョ: "gyo",
      シャ: "sha",
      シュ: "shu",
      ショ: "sho",
      ジャ: "ja",
      ジュ: "ju",
      ジョ: "jo",
      チャ: "cha",
      チュ: "chu",
      チョ: "cho",
      ニャ: "nya",
      ニュ: "nyu",
      ニョ: "nyo",
      ヒャ: "hya",
      ヒュ: "hyu",
      ヒョ: "hyo",
      ビャ: "bya",
      ビュ: "byu",
      ビョ: "byo",
      ピャ: "pya",
      ピュ: "pyu",
      ピョ: "pyo",
      ミャ: "mya",
      ミュ: "myu",
      ミョ: "myo",
      リャ: "rya",
      リュ: "ryu",
      リョ: "ryo",
    },
  },
];

export const kanjiChart = [
  { kanji: "一", meaning: "one" },
  { kanji: "二", meaning: "two" },
  { kanji: "三", meaning: "three" },
  { kanji: "四", meaning: "four" },
  { kanji: "五", meaning: "five" },
  { kanji: "六", meaning: "six" },
  { kanji: "七", meaning: "seven" },
  { kanji: "八", meaning: "eight" },
  { kanji: "九", meaning: "nine" },
  { kanji: "十", meaning: "ten" },
  { kanji: "百", meaning: "hundred" },
  { kanji: "千", meaning: "thousand" },
  { kanji: "万", meaning: "ten thousand" },
  { kanji: "円", meaning: "yen" },
  { kanji: "日", meaning: "day" },
  { kanji: "月", meaning: "month" },
  { kanji: "火", meaning: "fire" },
  { kanji: "水", meaning: "water" },
  { kanji: "木", meaning: "tree" },
  { kanji: "金", meaning: "gold" },
  { kanji: "土", meaning: "earth" },
];
